#### Publish tags to docker hub
name: Deploy Base Image to Docker Hub for tags
on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    name: Deploy to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
      - uses: olegtarasov/get-tag@v2
        name: Set tag envronment variable
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Run Buildx
        run: |
          cd ${{github.workspace}}/base && docker buildx build \
            --platform linux/arm,linux/arm64,linux/amd64 \
            --output "type=image,push=true" \
            --no-cache \
            --file .base/Dockerfile . \
            --compress \
            --tag netdaemon/base:latest \
            --tag netdaemon/base:${GIT_TAG_NAME}
